
build:
  image: zephyrprojectrtos/zephyr-build

  before_script:
    - west init -l .
    - west update
    - west config --global zephyr.base-prefer configfile
    - west zephyr-export

  script:
    - west build -b nucleo_wb55rg -- -DSHIELD=petejohanson_handwire
