variables:
  CI_BUILD_IMAGE: $CI_REGISTRY_IMAGE/zmk-build

build:
  image: $CI_BUILD_IMAGE

  variables:
    GIT_CLONE_PATH: $CI_PROJECT_DIR/zmk

  before_script:
    - west init -l .
    - west update
    - west config --global zephyr.base-prefer configfile
    - west zephyr-export

  script:
    - west build -b nucleo_wb55rg -- -DSHIELD=petejohanson_handwire

build:dockerimage:
  services:
    - docker:stable-dind

  image: docker:stable


  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_BUILD_IMAGE:latest || true
    - docker build --cache-from $CI_BUILD_IMAGE:latest -t $CI_BUILD_IMAGE:latest .
    - docker push $CI_BUILD_IMAGE:latest
