
build:
  image: zephyrprojectrtos/zephyr-build

  before_script:
    - west init -l .
    - west update
    - west config --global zephyr.base-prefer configfile
    - west zephyr-export
    - pip3 install --user -r ../zephyr/scripts/requirements.txt

  script:
    - west build -b nucleo_wb55rg -- -DSHIELD=petejohanson_handwire

build:dockerimage:
  services:
    - docker:stable-dind

  image: docker:stable

  script:
    - docker build .
