on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Basic build of the ZMK firmware
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path:
            - modules/
            - tools/
            - zephyr/
            - bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: ./.github/actions/zephyr-west # Uses an action in the root directory
        id: west-init
        with:
          command: 'init'
          command-args: '-l app'
      - name: West Update
        uses: ./.github/actions/zephyr-west # Uses an action in the root directory
        id: west-update
        with:
          command: 'update'
      - name: West Config Zephyr Base
        uses: ./.github/actions/zephyr-west # Uses an action in the root directory
        id: west-config
        with:
          command: 'config'
          command-args: '--global zephyr.base-prefer configfile'
      - name: West Zephyr Export
        uses: ./.github/actions/zephyr-west # Uses an action in the root directory
        id: west-zephyr-export
        with:
          command: 'zephyr-export'
      - name: West Build
        uses: ./.github/actions/zephyr-west # Uses an action in the root directory
        id: west-build
        with:
          command: 'build'
          command-args: '-s app -b nucleo_wb55rg -- -DSHIELD=petejohanson_handwire'
