name: doc-checks

on:
  push:
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: docs
      - name: ESLint
        run: npm run lint
        working-directory: docs
  prettier:
    runs-on: ubuntu-latest
    name: Prettier

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: docs
      - name: Prettier Check
        run: npm run prettier:check
        working-directory: docs
