name: Tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "app/tests/**"
      - "app/src/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "app/tests/**"
      - "app/src/**"

jobs:
  integration_test:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.3
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: 3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            3-${{ runner.os }}-build-${{ env.cache-name }}-
            3-${{ runner.os }}-build-
            3-${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: West init
        run: west init -l app
      - name: West update
        run: west update
      - name: West config Zephyr base
        run: west config --global zephyr.base-prefer configfile
      - name: West Zephyr export
        run: west zephyr-export
      - name: Test all
        run: west test
      - name: Archive build
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: "log-files"
          path: app/build/**/*.log
